version: '2.2'

services:
   app:
      image: book-shop:1.0
      ports:
      - 8080:8080
      environment:
         SPRING_REDIS_HOST: redis
         SPRING_REDIS_PORT: 6379
         SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book_shop
         SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
         SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
         SPRING_RABBITMQ_HOST: rabbitmq
      depends_on:
         mysql:
            condition: service_healthy
         rabbitmq:
            condition: service_healthy
         redis:
            condition: service_healthy

   mysql:
      image: mysql:8.0
      environment:
         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
         MYSQL_DATABASE: ${MYSQL_DATABASE}
      ports:
      - 3307:3306
      healthcheck:
         test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
         interval: 2s
         timeout: 5s
         retries: 5
      
   rabbitmq:
      image: rabbitmq:3-management
      ports:
      - 5673:5672
      - 15673:15672
      healthcheck:
         test: ["CMD", "rabbitmq-diagnostics", "status"]
         interval: 2s
         timeout: 5s
         retries: 5
      
   redis:
      image: redis:7
      ports: 
      - 6378:6379
      healthcheck:
         test: ["CMD", "redis-cli", "ping"]
         interval: 2s
         timeout: 5s
         retries: 5
