version: '2.2'

services:
   app:
      build:
         context: .
         dockerfile: Dockerfile
      image: book-shop:1.0
      env_file:
         - .env
      environment:
         - SPRING_PROFILES_ACTIVE=prod
      ports:
      - 8080:8080
      depends_on:
         mysql:
            condition: service_healthy
         rabbitmq:
            condition: service_healthy
         redis:
            condition: service_healthy
   
   mailhog:
      image: mailhog/mailhog
      ports:
         - "8025:8025"
         - "1025:1025"
   mysql:
      image: mysql:8.0
      environment:
         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
         MYSQL_DATABASE: ${MYSQL_DATABASE}
      ports:
         - "3307:3306"
      healthcheck:
         test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
         interval: 5s
         timeout: 15s
         retries: 10
      
   rabbitmq:
      image: rabbitmq:3-management
      ports:
      - "5673:5672"
      - "15673:15672"
      healthcheck:
         test: ["CMD", "rabbitmq-diagnostics", "status"]
         interval: 2s
         timeout: 5s
         retries: 5
      
   redis:
      image: redis:7
      ports: 
      - "6378:6379"
      healthcheck:
         test: ["CMD", "redis-cli", "ping"]
         interval: 2s
         timeout: 5s
         retries: 5
